spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderflow
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    toy.orderflow: DEBUG
